# WORD_EMBEDDING_SRC = 'word2vec'
# WORD_EMBEDDING_LENGTH = 50

WORD_EMBEDDING_SRC = 'bert'
WORD_EMBEDDING_LENGTH = 768

SENTENCE_TRUNCATION_LENGTH = 10
SENTENCE_EMBEDDING_LENGTH = WORD_EMBEDDING_LENGTH * SENTENCE_TRUNCATION_LENGTH
